# title can be used instead of 'url' item
['https://www.youtube.com/channel/UCsUj0dszADCGbF3gNrQEuSQ']
q = 'best'
r = 'archive' # 'r' or 'regex' means 'regex_title' and 'regex_desc'

['Ceres Fauna']
u = 'https://www.youtube.com/channel/UCO_aKKYxn4tvrqPjcTzZ6EQ'
quality = '480p' # q
regex_title = 'asmr|archive' 

['Nanashi Mumei']
url = 'https://www.youtube.com/channel/UC3n5uGu18FoCy23ggWWp8tA' # u
quality = '360p'
delete = true # will remove 'Nanashi Mumei' if she is streaming

# Hakos Baelz
['@https://www.youtube.com/channel/UCgmPnx-EEeOrZSg5Tiw7ZRQ']
# will remove 'Hakos Baelz' too, because url starts with '@'
f = 'alive'
q = 'worst' # not work in ytarchive, will fallback to 'best'

['Ouro Kronii'] 
folder = 'alive' # f
u = 'https://www.youtube.com/channel/UCmbs8T6MWqUHP1tIQvSgKrg'

# all comments will be destroyed if config is overwritten due to channel deletion, sorry T_T 